[global]
   workgroup = WORKGROUP
   server string = LibraryIT Server
   security = user
   map to guest = never
   log file = /logs/libraryit.log
   log level = 1
   max log size = 1000

[ebooks]
   path = /libraryit/ebooks
   valid users = @readonly, @staff
   read only = yes
   write list = @staff
   browseable = yes

[papers]
   path = /libraryit/papers
   valid users = @readonly, @staff
   read only = yes
   write list = @staff
   browseable = yes

[docs]
   path = /libraryit/docs
   valid users = @readonly, @staff
   read only = yes
   write list = librarian
   browseable = yes
   force create mode = 0664
   force directory mode = 0775

[sourcecode]
   path = /libraryit/sourcecode
   valid users = @staff
   read only = yes
   write list = @staff
   browseable = yes
